### ISSUE TITLE
Dosya açma hatası

### ISSUE THREAD

**Issue by WormerKing** [AliKilicoglu/Open-Editor#1]
Dosya açtıktan sonra(python dosyası açtım) yeni bir dosya açmaya çalıştığımda önceki dosyanın altından devam ediyor

**Comment by AliKilicoglu** [comment]
teşekürler şuan onun üzerinde çalışıyorum

**Comment by AliKilicoglu** [comment]
düzelttim

**Comment by WormerKing** [comment]
Bide bir klasör açıp içine import edilecek dosyaları atmanız taşınabilirlik için iyi olur.
