### ISSUE TITLE
bcvc version 10 u sil bende sileyim

### ISSUE THREAD

**Issue by barron4335** [AliKilicoglu/Open-Editor#4]
hem buradan hemde bilgisayarından bcvc10 versiyonumu sil bende silicem aksi halde tehdit ettiğine dair bende savunmamı yaparım daha önce uyarmıştım ay çok korktum diye alay etmiştin şimdi ne oldu söylesene ?

**Comment by barron4335** [comment]
> hem buradan hemde bilgisayarından bcvc10 versiyonumu sil bende silicem aksi halde tehdit ettiğine dair bende savunmamı yaparım daha önce uyarmıştım ay çok korktum diye alay etmiştin şimdi ne oldu söylesene ?

Anlaşılan cevap yok

**Comment by AliKilicoglu** [comment]
sattım bile
